name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Yarn
        run: npm install -g yarn
        shell: bash

      # - name: Cache dependencies
      #   id: cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ./
      #     key: modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        shell: bash

      - run: yarn nx affected -t lint test build e2e-ci
